apiVersion: v1
kind: Service
metadata:
  annotations:
    purpose: homework
  name: homework-svc
  labels:
    app: hw
  namespace: homework
spec:
  type: NodePort
  selector:
    app: hw
  ports:
    - protocol: TCP
      port: 32000
      targetPort: 5000
